import subprocess
import os
import re
import json
import sys
import argparse
from pathlib import Path

def extract_data_from_ngspice_output(path_to_file):
    """ Parses the output file generated by ngspice and
    returns a json containing points to plot graph.
    (Adapted from simulationAPI/helpers/parse.py)
    """
    try:
        if not os.path.exists(path_to_file):
            return None
            
        with open(path_to_file, 'r') as f:
            f_contents = f.readlines()
            graph = False

            curernt_headers = []
            total_number_of_tables = 0
            if(len(f_contents) > 3):
                if('---' in f_contents[2]):
                    graph = True

            if(not graph):
                json_data = {"data": [], "graph": "false"}
                for line in f_contents:
                    contents_of_line = line.split()
                    if contents_of_line:
                        json_data["data"].append(contents_of_line)
            else:
                json_data = {"data": [], "graph": "true"}
                for line in f_contents:
                    contents_of_line = line.split()
                    if not contents_of_line:
                        continue

                    if('Index' in contents_of_line):
                        line_set = contents_of_line

                        if(line_set != curernt_headers):
                            curernt_headers = line_set
                            json_data["data"].append(
                                {"labels": [], "x": [], "y": []})
                            index = len(json_data["data"]) - 1
                            for x in range(2, len(curernt_headers)):
                                json_data["data"][index]["y"].append([])

                            for x in range(1, len(curernt_headers)):
                                json_data["data"][index]["labels"].append(
                                    curernt_headers[x])
                                total_number_of_tables += 1
                    else:
                        m = re.match('[0-9]+', line)
                        if(m):
                            index = len(json_data["data"]) - 1
                            data = json_data["data"][index]
                            data["x"].append(contents_of_line[1])

                            for x in range(len(data["y"])):
                                if len(contents_of_line) > x + 2:
                                    data["y"][x].append(contents_of_line[x+2])
                
                json_data["total_number_of_tables"] = total_number_of_tables - len(json_data["data"])
        return json_data

    except Exception as e:
        return {"error": str(e)}

def inject_ngbehavior_ps(netlist_text):
    """
    Inject 'set ngbehavior=ps' into the .control block of a netlist.
    (Adapted from simulationAPI/helpers/ngspice_helper.py)
    """
    lines = netlist_text.split('\n')
    for i, line in enumerate(lines):
        stripped = line.strip().lower()
        if stripped.startswith('.control'):
            lines.insert(i + 1, 'set ngbehavior=ps')
            return '\n'.join(lines)
    return netlist_text

def run_simulation(netlist_content):
    temp_dir = Path("/tmp/simulation_run")
    temp_dir.mkdir(parents=True, exist_ok=True)
    
    # In eSim-Cloud, the netlist is expected to have a .control block
    # that writes data to 'data.txt'.
    netlist_content = inject_ngbehavior_ps(netlist_content)
    
    netlist_path = temp_dir / "circuit.cir"
    with open(netlist_path, "w") as f:
        f.write(netlist_content)
    
    try:
        # -b for batch mode
        # -a for automatically generate raw file (sometimes used)
        # The backend uses -ab
        proc = subprocess.Popen(['ngspice', '-ab', str(netlist_path)],
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                cwd=temp_dir)
        stdout, stderr = proc.communicate()
        
        data_file = temp_dir / "data.txt"
        parsed_data = extract_data_from_ngspice_output(str(data_file))
        
        if parsed_data and "error" not in parsed_data:
            return parsed_data
        else:
            return {
                "success": False,
                "stdout": stdout.decode("utf-8", errors="replace"),
                "stderr": stderr.decode("utf-8", errors="replace"),
                "parsing_error": parsed_data.get("error") if parsed_data else "No data.txt generated"
            }
    except Exception as e:
        return {"success": False, "error": str(e)}
    finally:
        # Cleanup
        try:
            for item in temp_dir.iterdir():
                item.unlink()
            temp_dir.rmdir()
        except:
            pass

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Run NGSPICE simulation.')
    parser.add_argument('file', nargs='?', help='Path to circuit file (if omitted, read from stdin)')
    args = parser.parse_args()

    if args.file:
        try:
            with open(args.file, 'r') as f:
                content = f.read()
        except Exception as e:
            print(json.dumps({"success": False, "error": f"Failed to read file: {e}"}))
            sys.exit(1)
    else:
        content = sys.stdin.read()

    if not content:
        print(json.dumps({"success": False, "error": "No input provided"}))
        sys.exit(1)

    result = run_simulation(content)
    print(json.dumps(result))
